### ISSUE TITLE
mp3 to aac

### ISSUE THREAD

**Issue by yshterev** [emliri/multimedia-js#2]
Hi @tchakabam - Is it possible to convert mp3 to aac before muxing it into the mp4 file ?

**Comment by tchakabam** [comment]
Hi @yshterev 

provided an AAC encoder in JS one could write a framework unit that does that, sure :)

but do you have an AAC encoder? I only know there exists an AAC decoder (which could of course be integrated, see [1])

[1] https://github.com/audiocogs/aac.js

**Comment by tchakabam** [comment]
also one would need to integrate MP3 decoding here, probably based on [2]. 

on the other hand, mp3 encoding in js also exists here [3]

[2] https://github.com/audiocogs/mp3.js 
[3] https://github.com/zhuker/lamejs

implementing/porting AAC encoding might involve license issues? 

it is definitely possible, as decoders have been ported from native code likewise using asm.js etc.
